profile: full

ceip_policy_disclosed: true # Installation fails if this is set to 'false'
buildservice:
  kp_default_repository: "private-harbor.tanzu.lab/tap/build-service"
  kp_default_repository_username: "admin"
  kp_default_repository_password: "VMware1!"
  enable_automatic_dependency_updates: false
  exclude_dependencies: true
  ca_cert_data: |
      -----BEGIN CERTIFICATE-----
      MIIFazCCA1OgAwIBAgIUCEqci08l6e7BjBtgKz0RIdGgp3cwDQYJKoZIhvcNAQEN
      BQAwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoM
      GEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDAeFw0yMzAyMTYwOTUxMDlaFw0zMzAy
      MTMwOTUxMDlaMEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEw
      HwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwggIiMA0GCSqGSIb3DQEB
      AQUAA4ICDwAwggIKAoICAQC0NsXK3x+cVcHvXp4f6zJjxcqsPnV3h/eT0VDrzXpy
      3QIkgmCpBxdKi6QS5p1Ze+K3EgKgu4uK+Rzfs35w3iMv7wjoUVZ9EH+lXLghyW8G
      WNXnjo75ibKGRvY8W2ujTl+S8W7FAxeI8UHWvveMPkyzYZJyCnqBc2dB3XBjnGmZ
      MI+Ex0ub0G5aSoSq2WrfMFb0RXsyR40Z+Jqpl4+fiYmISwfwoetsaXMxzUo5Jkcd
      s52J5Huoy3kkkXWjoxMVJFYb18DsS5edcO06C0mdwo0Rf0sW5KvAvSEIZ4jjOP33
      1r5TwzKMPQSXoo8B3NRvUy7SijRK1ycIcr1eZNxgTnoXU0ZeLU8xvQlSvEsQe+Fb
      912ccu4dKfNztPfB+f+rlqI6nQw/scJbeLVpk88C5WBy9M8udmH5dhBPyWlKb/ok
      GAaHiYzIHDFbeMQdmuqwtaK9usHLSGVwNRF6cWQbb2UyHiTR0sDy6BsZ949R1Tro
      Ubj6YXURzr5r2sjdvuXjkR0FUSF5HpSsw/uGLNSm0IFiGUg1lgo38kFzZ8xPSxII
      NlfN+rLXfgcVNgfMAJIGns3lGcv0Vs+wrNHOEoGClqm3c9YDm4GW27/66s0P1etK
      yw+3JCGPTMXj3SIzV7aefWi2uermjLA2DqrM64RMPaqaeTkRKlfB/Uv6Fjxhy17o
      3QIDAQABo1MwUTAdBgNVHQ4EFgQUvEPLdaWR5Rwh1zjgkC1uXqZjSeEwHwYDVR0j
      BBgwFoAUvEPLdaWR5Rwh1zjgkC1uXqZjSeEwDwYDVR0TAQH/BAUwAwEB/zANBgkq
      hkiG9w0BAQ0FAAOCAgEAH1zq6j0aiG1XSIvrOAwxi6uIdFKio/9rDwShtMjQ8XvP
      zCrCUw1S4XlxcmFV92eoMNnpkoj4ESw3qaJ+vVJJLibyBZq8TV46i9/Wy/nUnEEU
      w2TG2NKBVernWxO+5t0xXpVH3Ru71DSomQ+fvgPQkkYoEqcalWT44r83jZi2HeYt
      gEjesDzKSImFJpGEwGJD5s2nL3Pfjg9CjqKK9gHOlgBN0z/OroKnpoPMHuymU5rt
      zHilfRC+OoC2tP2yK7fkW7xrVMFVdH8AUD1U5cghHzyszBeFjHOvkvWXTXmHlOtJ
      t5C137XSsSsIahDr3IWFTb6sF9vRchoXozkrfDX7ZpLcF0U+cJygBA6a6qoQe/CW
      95z9ZzNa1iCk40RsCo+gqYzGExEsTBtYJd48zXtFXBE/0ieX/0NvGDrA8QNZgHp5
      fWyzEFoGOAW9XgEL0ne9vqiCdilRIkwrXGjV/2meceHhwwrhVTcwHMrDgpEdwmvD
      Prd8TNn5nE+pJdg+RRiP6MpDJg/aWRlHOJfAINg2ME2ZGlZz1ew45cBM+gE2RBLl
      Aof5ylUgIfjXqoq7M9zYCJP7Xqyd2Ngqb3/s88QnaO7VdZwDIL3RnNNryCWAPQeA
      v8yM/1oVslc7OGDgb2mjpzYBLj+X7qhP9UYw3oujB1wXMA2GDbT8mbLa22OUpA4=
      -----END CERTIFICATE-----

scanning:
  metadataStore:
    url: ""

accelerator:
  domain: user01.tanzu.lab
  samples:
  # Prevent repeated polling of github to pull accelerators
    include: true

supply_chain: basic

ootb_supply_chain_basic:
  registry:
    server: "private-harbor.tanzu.lab"
    repository: "tap/supply-chain"

learningcenter:
  ingressDomain: "user01.tanzu.lab"
  ingressClass: contour
  ca_cert_data: |
      -----BEGIN CERTIFICATE-----
      MIIFazCCA1OgAwIBAgIUCEqci08l6e7BjBtgKz0RIdGgp3cwDQYJKoZIhvcNAQEN
      BQAwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoM
      GEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDAeFw0yMzAyMTYwOTUxMDlaFw0zMzAy
      MTMwOTUxMDlaMEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEw
      HwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwggIiMA0GCSqGSIb3DQEB
      AQUAA4ICDwAwggIKAoICAQC0NsXK3x+cVcHvXp4f6zJjxcqsPnV3h/eT0VDrzXpy
      3QIkgmCpBxdKi6QS5p1Ze+K3EgKgu4uK+Rzfs35w3iMv7wjoUVZ9EH+lXLghyW8G
      WNXnjo75ibKGRvY8W2ujTl+S8W7FAxeI8UHWvveMPkyzYZJyCnqBc2dB3XBjnGmZ
      MI+Ex0ub0G5aSoSq2WrfMFb0RXsyR40Z+Jqpl4+fiYmISwfwoetsaXMxzUo5Jkcd
      s52J5Huoy3kkkXWjoxMVJFYb18DsS5edcO06C0mdwo0Rf0sW5KvAvSEIZ4jjOP33
      1r5TwzKMPQSXoo8B3NRvUy7SijRK1ycIcr1eZNxgTnoXU0ZeLU8xvQlSvEsQe+Fb
      912ccu4dKfNztPfB+f+rlqI6nQw/scJbeLVpk88C5WBy9M8udmH5dhBPyWlKb/ok
      GAaHiYzIHDFbeMQdmuqwtaK9usHLSGVwNRF6cWQbb2UyHiTR0sDy6BsZ949R1Tro
      Ubj6YXURzr5r2sjdvuXjkR0FUSF5HpSsw/uGLNSm0IFiGUg1lgo38kFzZ8xPSxII
      NlfN+rLXfgcVNgfMAJIGns3lGcv0Vs+wrNHOEoGClqm3c9YDm4GW27/66s0P1etK
      yw+3JCGPTMXj3SIzV7aefWi2uermjLA2DqrM64RMPaqaeTkRKlfB/Uv6Fjxhy17o
      3QIDAQABo1MwUTAdBgNVHQ4EFgQUvEPLdaWR5Rwh1zjgkC1uXqZjSeEwHwYDVR0j
      BBgwFoAUvEPLdaWR5Rwh1zjgkC1uXqZjSeEwDwYDVR0TAQH/BAUwAwEB/zANBgkq
      hkiG9w0BAQ0FAAOCAgEAH1zq6j0aiG1XSIvrOAwxi6uIdFKio/9rDwShtMjQ8XvP
      zCrCUw1S4XlxcmFV92eoMNnpkoj4ESw3qaJ+vVJJLibyBZq8TV46i9/Wy/nUnEEU
      w2TG2NKBVernWxO+5t0xXpVH3Ru71DSomQ+fvgPQkkYoEqcalWT44r83jZi2HeYt
      gEjesDzKSImFJpGEwGJD5s2nL3Pfjg9CjqKK9gHOlgBN0z/OroKnpoPMHuymU5rt
      zHilfRC+OoC2tP2yK7fkW7xrVMFVdH8AUD1U5cghHzyszBeFjHOvkvWXTXmHlOtJ
      t5C137XSsSsIahDr3IWFTb6sF9vRchoXozkrfDX7ZpLcF0U+cJygBA6a6qoQe/CW
      95z9ZzNa1iCk40RsCo+gqYzGExEsTBtYJd48zXtFXBE/0ieX/0NvGDrA8QNZgHp5
      fWyzEFoGOAW9XgEL0ne9vqiCdilRIkwrXGjV/2meceHhwwrhVTcwHMrDgpEdwmvD
      Prd8TNn5nE+pJdg+RRiP6MpDJg/aWRlHOJfAINg2ME2ZGlZz1ew45cBM+gE2RBLl
      Aof5ylUgIfjXqoq7M9zYCJP7Xqyd2Ngqb3/s88QnaO7VdZwDIL3RnNNryCWAPQeA
      v8yM/1oVslc7OGDgb2mjpzYBLj+X7qhP9UYw3oujB1wXMA2GDbT8mbLa22OUpA4=
      -----END CERTIFICATE-----

appliveview:
  ingressDomain: "user01.tanzu.lab"
  ingressEnabled: false

appliveview_connector:
  backend:
    ingressEnabled: false
    caCertData: |-
      -----BEGIN CERTIFICATE-----
      MIIFazCCA1OgAwIBAgIUCEqci08l6e7BjBtgKz0RIdGgp3cwDQYJKoZIhvcNAQEN
      BQAwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoM
      GEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDAeFw0yMzAyMTYwOTUxMDlaFw0zMzAy
      MTMwOTUxMDlaMEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEw
      HwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwggIiMA0GCSqGSIb3DQEB
      AQUAA4ICDwAwggIKAoICAQC0NsXK3x+cVcHvXp4f6zJjxcqsPnV3h/eT0VDrzXpy
      3QIkgmCpBxdKi6QS5p1Ze+K3EgKgu4uK+Rzfs35w3iMv7wjoUVZ9EH+lXLghyW8G
      WNXnjo75ibKGRvY8W2ujTl+S8W7FAxeI8UHWvveMPkyzYZJyCnqBc2dB3XBjnGmZ
      MI+Ex0ub0G5aSoSq2WrfMFb0RXsyR40Z+Jqpl4+fiYmISwfwoetsaXMxzUo5Jkcd
      s52J5Huoy3kkkXWjoxMVJFYb18DsS5edcO06C0mdwo0Rf0sW5KvAvSEIZ4jjOP33
      1r5TwzKMPQSXoo8B3NRvUy7SijRK1ycIcr1eZNxgTnoXU0ZeLU8xvQlSvEsQe+Fb
      912ccu4dKfNztPfB+f+rlqI6nQw/scJbeLVpk88C5WBy9M8udmH5dhBPyWlKb/ok
      GAaHiYzIHDFbeMQdmuqwtaK9usHLSGVwNRF6cWQbb2UyHiTR0sDy6BsZ949R1Tro
      Ubj6YXURzr5r2sjdvuXjkR0FUSF5HpSsw/uGLNSm0IFiGUg1lgo38kFzZ8xPSxII
      NlfN+rLXfgcVNgfMAJIGns3lGcv0Vs+wrNHOEoGClqm3c9YDm4GW27/66s0P1etK
      yw+3JCGPTMXj3SIzV7aefWi2uermjLA2DqrM64RMPaqaeTkRKlfB/Uv6Fjxhy17o
      3QIDAQABo1MwUTAdBgNVHQ4EFgQUvEPLdaWR5Rwh1zjgkC1uXqZjSeEwHwYDVR0j
      BBgwFoAUvEPLdaWR5Rwh1zjgkC1uXqZjSeEwDwYDVR0TAQH/BAUwAwEB/zANBgkq
      hkiG9w0BAQ0FAAOCAgEAH1zq6j0aiG1XSIvrOAwxi6uIdFKio/9rDwShtMjQ8XvP
      zCrCUw1S4XlxcmFV92eoMNnpkoj4ESw3qaJ+vVJJLibyBZq8TV46i9/Wy/nUnEEU
      w2TG2NKBVernWxO+5t0xXpVH3Ru71DSomQ+fvgPQkkYoEqcalWT44r83jZi2HeYt
      gEjesDzKSImFJpGEwGJD5s2nL3Pfjg9CjqKK9gHOlgBN0z/OroKnpoPMHuymU5rt
      zHilfRC+OoC2tP2yK7fkW7xrVMFVdH8AUD1U5cghHzyszBeFjHOvkvWXTXmHlOtJ
      t5C137XSsSsIahDr3IWFTb6sF9vRchoXozkrfDX7ZpLcF0U+cJygBA6a6qoQe/CW
      95z9ZzNa1iCk40RsCo+gqYzGExEsTBtYJd48zXtFXBE/0ieX/0NvGDrA8QNZgHp5
      fWyzEFoGOAW9XgEL0ne9vqiCdilRIkwrXGjV/2meceHhwwrhVTcwHMrDgpEdwmvD
      Prd8TNn5nE+pJdg+RRiP6MpDJg/aWRlHOJfAINg2ME2ZGlZz1ew45cBM+gE2RBLl
      Aof5ylUgIfjXqoq7M9zYCJP7Xqyd2Ngqb3/s88QnaO7VdZwDIL3RnNNryCWAPQeA
      v8yM/1oVslc7OGDgb2mjpzYBLj+X7qhP9UYw3oujB1wXMA2GDbT8mbLa22OUpA4=
      -----END CERTIFICATE-----

tap_gui:
  service_type: ClusterIP
  ingressEnabled: "true"
  ingressDomain: "user01.tanzu.lab"
  app_config:
    app:
      baseUrl: https://tap-gui.user01.tanzu.lab
    catalog:
      locations:
        - type: url
          target: https://github.com/tanzukorea/TAP-HOL/blob/main/catalog/catalog-info.yaml
    integrations:
      github:
        - host: github.com
          token: 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
    backend:
      baseUrl: https://tap-gui.user01.tanzu.lab
      cors:
      origins: https://tap-gui.user01.tanzu.lab
      reading:
        allow:
          - host: acc-server.accelerator-system.svc.cluster.local

metadata_store:
  ingress_domain: "user01.tanzu.lab"
  app_service_type: ClusterIP # (optional) Defaults to LoadBalancer. Change to NodePort for distributions that don't support LoadBalancer
  ingress_enabled: "true"
  ns_for_export_app_cert: "default"
  targetImagePullSecret: "tap-registry"
  ca_cert_data: |
      -----BEGIN CERTIFICATE-----
      MIIFazCCA1OgAwIBAgIUCEqci08l6e7BjBtgKz0RIdGgp3cwDQYJKoZIhvcNAQEN
      BQAwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoM
      GEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDAeFw0yMzAyMTYwOTUxMDlaFw0zMzAy
      MTMwOTUxMDlaMEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEw
      HwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwggIiMA0GCSqGSIb3DQEB
      AQUAA4ICDwAwggIKAoICAQC0NsXK3x+cVcHvXp4f6zJjxcqsPnV3h/eT0VDrzXpy
      3QIkgmCpBxdKi6QS5p1Ze+K3EgKgu4uK+Rzfs35w3iMv7wjoUVZ9EH+lXLghyW8G
      WNXnjo75ibKGRvY8W2ujTl+S8W7FAxeI8UHWvveMPkyzYZJyCnqBc2dB3XBjnGmZ
      MI+Ex0ub0G5aSoSq2WrfMFb0RXsyR40Z+Jqpl4+fiYmISwfwoetsaXMxzUo5Jkcd
      s52J5Huoy3kkkXWjoxMVJFYb18DsS5edcO06C0mdwo0Rf0sW5KvAvSEIZ4jjOP33
      1r5TwzKMPQSXoo8B3NRvUy7SijRK1ycIcr1eZNxgTnoXU0ZeLU8xvQlSvEsQe+Fb
      912ccu4dKfNztPfB+f+rlqI6nQw/scJbeLVpk88C5WBy9M8udmH5dhBPyWlKb/ok
      GAaHiYzIHDFbeMQdmuqwtaK9usHLSGVwNRF6cWQbb2UyHiTR0sDy6BsZ949R1Tro
      Ubj6YXURzr5r2sjdvuXjkR0FUSF5HpSsw/uGLNSm0IFiGUg1lgo38kFzZ8xPSxII
      NlfN+rLXfgcVNgfMAJIGns3lGcv0Vs+wrNHOEoGClqm3c9YDm4GW27/66s0P1etK
      yw+3JCGPTMXj3SIzV7aefWi2uermjLA2DqrM64RMPaqaeTkRKlfB/Uv6Fjxhy17o
      3QIDAQABo1MwUTAdBgNVHQ4EFgQUvEPLdaWR5Rwh1zjgkC1uXqZjSeEwHwYDVR0j
      BBgwFoAUvEPLdaWR5Rwh1zjgkC1uXqZjSeEwDwYDVR0TAQH/BAUwAwEB/zANBgkq
      hkiG9w0BAQ0FAAOCAgEAH1zq6j0aiG1XSIvrOAwxi6uIdFKio/9rDwShtMjQ8XvP
      zCrCUw1S4XlxcmFV92eoMNnpkoj4ESw3qaJ+vVJJLibyBZq8TV46i9/Wy/nUnEEU
      w2TG2NKBVernWxO+5t0xXpVH3Ru71DSomQ+fvgPQkkYoEqcalWT44r83jZi2HeYt
      gEjesDzKSImFJpGEwGJD5s2nL3Pfjg9CjqKK9gHOlgBN0z/OroKnpoPMHuymU5rt
      zHilfRC+OoC2tP2yK7fkW7xrVMFVdH8AUD1U5cghHzyszBeFjHOvkvWXTXmHlOtJ
      t5C137XSsSsIahDr3IWFTb6sF9vRchoXozkrfDX7ZpLcF0U+cJygBA6a6qoQe/CW
      95z9ZzNa1iCk40RsCo+gqYzGExEsTBtYJd48zXtFXBE/0ieX/0NvGDrA8QNZgHp5
      fWyzEFoGOAW9XgEL0ne9vqiCdilRIkwrXGjV/2meceHhwwrhVTcwHMrDgpEdwmvD
      Prd8TNn5nE+pJdg+RRiP6MpDJg/aWRlHOJfAINg2ME2ZGlZz1ew45cBM+gE2RBLl
      Aof5ylUgIfjXqoq7M9zYCJP7Xqyd2Ngqb3/s88QnaO7VdZwDIL3RnNNryCWAPQeA
      v8yM/1oVslc7OGDgb2mjpzYBLj+X7qhP9UYw3oujB1wXMA2GDbT8mbLa22OUpA4=
      -----END CERTIFICATE-----

grype:
  namespace: "default" # (optional) Defaults to default namespace.
  targetImagePullSecret: "registry-credentials"


cnrs:
  domain_name: user01.tanzu.lab
  ingress:
    external:
      namespace: tanzu-system-ingress

contour:
  envoy:
    service:
      type: LoadBalancer

source_controller:
  ca_cert_data: |
      -----BEGIN CERTIFICATE-----
      MIIFazCCA1OgAwIBAgIUCEqci08l6e7BjBtgKz0RIdGgp3cwDQYJKoZIhvcNAQEN
      BQAwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoM
      GEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDAeFw0yMzAyMTYwOTUxMDlaFw0zMzAy
      MTMwOTUxMDlaMEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEw
      HwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwggIiMA0GCSqGSIb3DQEB
      AQUAA4ICDwAwggIKAoICAQC0NsXK3x+cVcHvXp4f6zJjxcqsPnV3h/eT0VDrzXpy
      3QIkgmCpBxdKi6QS5p1Ze+K3EgKgu4uK+Rzfs35w3iMv7wjoUVZ9EH+lXLghyW8G
      WNXnjo75ibKGRvY8W2ujTl+S8W7FAxeI8UHWvveMPkyzYZJyCnqBc2dB3XBjnGmZ
      MI+Ex0ub0G5aSoSq2WrfMFb0RXsyR40Z+Jqpl4+fiYmISwfwoetsaXMxzUo5Jkcd
      s52J5Huoy3kkkXWjoxMVJFYb18DsS5edcO06C0mdwo0Rf0sW5KvAvSEIZ4jjOP33
      1r5TwzKMPQSXoo8B3NRvUy7SijRK1ycIcr1eZNxgTnoXU0ZeLU8xvQlSvEsQe+Fb
      912ccu4dKfNztPfB+f+rlqI6nQw/scJbeLVpk88C5WBy9M8udmH5dhBPyWlKb/ok
      GAaHiYzIHDFbeMQdmuqwtaK9usHLSGVwNRF6cWQbb2UyHiTR0sDy6BsZ949R1Tro
      Ubj6YXURzr5r2sjdvuXjkR0FUSF5HpSsw/uGLNSm0IFiGUg1lgo38kFzZ8xPSxII
      NlfN+rLXfgcVNgfMAJIGns3lGcv0Vs+wrNHOEoGClqm3c9YDm4GW27/66s0P1etK
      yw+3JCGPTMXj3SIzV7aefWi2uermjLA2DqrM64RMPaqaeTkRKlfB/Uv6Fjxhy17o
      3QIDAQABo1MwUTAdBgNVHQ4EFgQUvEPLdaWR5Rwh1zjgkC1uXqZjSeEwHwYDVR0j
      BBgwFoAUvEPLdaWR5Rwh1zjgkC1uXqZjSeEwDwYDVR0TAQH/BAUwAwEB/zANBgkq
      hkiG9w0BAQ0FAAOCAgEAH1zq6j0aiG1XSIvrOAwxi6uIdFKio/9rDwShtMjQ8XvP
      zCrCUw1S4XlxcmFV92eoMNnpkoj4ESw3qaJ+vVJJLibyBZq8TV46i9/Wy/nUnEEU
      w2TG2NKBVernWxO+5t0xXpVH3Ru71DSomQ+fvgPQkkYoEqcalWT44r83jZi2HeYt
      gEjesDzKSImFJpGEwGJD5s2nL3Pfjg9CjqKK9gHOlgBN0z/OroKnpoPMHuymU5rt
      zHilfRC+OoC2tP2yK7fkW7xrVMFVdH8AUD1U5cghHzyszBeFjHOvkvWXTXmHlOtJ
      t5C137XSsSsIahDr3IWFTb6sF9vRchoXozkrfDX7ZpLcF0U+cJygBA6a6qoQe/CW
      95z9ZzNa1iCk40RsCo+gqYzGExEsTBtYJd48zXtFXBE/0ieX/0NvGDrA8QNZgHp5
      fWyzEFoGOAW9XgEL0ne9vqiCdilRIkwrXGjV/2meceHhwwrhVTcwHMrDgpEdwmvD
      Prd8TNn5nE+pJdg+RRiP6MpDJg/aWRlHOJfAINg2ME2ZGlZz1ew45cBM+gE2RBLl
      Aof5ylUgIfjXqoq7M9zYCJP7Xqyd2Ngqb3/s88QnaO7VdZwDIL3RnNNryCWAPQeA
      v8yM/1oVslc7OGDgb2mjpzYBLj+X7qhP9UYw3oujB1wXMA2GDbT8mbLa22OUpA4=
      -----END CERTIFICATE-----

shared:
  ca_cert_data: |
      -----BEGIN CERTIFICATE-----
      MIIFazCCA1OgAwIBAgIUCEqci08l6e7BjBtgKz0RIdGgp3cwDQYJKoZIhvcNAQEN
      BQAwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoM
      GEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDAeFw0yMzAyMTYwOTUxMDlaFw0zMzAy
      MTMwOTUxMDlaMEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEw
      HwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwggIiMA0GCSqGSIb3DQEB
      AQUAA4ICDwAwggIKAoICAQC0NsXK3x+cVcHvXp4f6zJjxcqsPnV3h/eT0VDrzXpy
      3QIkgmCpBxdKi6QS5p1Ze+K3EgKgu4uK+Rzfs35w3iMv7wjoUVZ9EH+lXLghyW8G
      WNXnjo75ibKGRvY8W2ujTl+S8W7FAxeI8UHWvveMPkyzYZJyCnqBc2dB3XBjnGmZ
      MI+Ex0ub0G5aSoSq2WrfMFb0RXsyR40Z+Jqpl4+fiYmISwfwoetsaXMxzUo5Jkcd
      s52J5Huoy3kkkXWjoxMVJFYb18DsS5edcO06C0mdwo0Rf0sW5KvAvSEIZ4jjOP33
      1r5TwzKMPQSXoo8B3NRvUy7SijRK1ycIcr1eZNxgTnoXU0ZeLU8xvQlSvEsQe+Fb
      912ccu4dKfNztPfB+f+rlqI6nQw/scJbeLVpk88C5WBy9M8udmH5dhBPyWlKb/ok
      GAaHiYzIHDFbeMQdmuqwtaK9usHLSGVwNRF6cWQbb2UyHiTR0sDy6BsZ949R1Tro
      Ubj6YXURzr5r2sjdvuXjkR0FUSF5HpSsw/uGLNSm0IFiGUg1lgo38kFzZ8xPSxII
      NlfN+rLXfgcVNgfMAJIGns3lGcv0Vs+wrNHOEoGClqm3c9YDm4GW27/66s0P1etK
      yw+3JCGPTMXj3SIzV7aefWi2uermjLA2DqrM64RMPaqaeTkRKlfB/Uv6Fjxhy17o
      3QIDAQABo1MwUTAdBgNVHQ4EFgQUvEPLdaWR5Rwh1zjgkC1uXqZjSeEwHwYDVR0j
      BBgwFoAUvEPLdaWR5Rwh1zjgkC1uXqZjSeEwDwYDVR0TAQH/BAUwAwEB/zANBgkq
      hkiG9w0BAQ0FAAOCAgEAH1zq6j0aiG1XSIvrOAwxi6uIdFKio/9rDwShtMjQ8XvP
      zCrCUw1S4XlxcmFV92eoMNnpkoj4ESw3qaJ+vVJJLibyBZq8TV46i9/Wy/nUnEEU
      w2TG2NKBVernWxO+5t0xXpVH3Ru71DSomQ+fvgPQkkYoEqcalWT44r83jZi2HeYt
      gEjesDzKSImFJpGEwGJD5s2nL3Pfjg9CjqKK9gHOlgBN0z/OroKnpoPMHuymU5rt
      zHilfRC+OoC2tP2yK7fkW7xrVMFVdH8AUD1U5cghHzyszBeFjHOvkvWXTXmHlOtJ
      t5C137XSsSsIahDr3IWFTb6sF9vRchoXozkrfDX7ZpLcF0U+cJygBA6a6qoQe/CW
      95z9ZzNa1iCk40RsCo+gqYzGExEsTBtYJd48zXtFXBE/0ieX/0NvGDrA8QNZgHp5
      fWyzEFoGOAW9XgEL0ne9vqiCdilRIkwrXGjV/2meceHhwwrhVTcwHMrDgpEdwmvD
      Prd8TNn5nE+pJdg+RRiP6MpDJg/aWRlHOJfAINg2ME2ZGlZz1ew45cBM+gE2RBLl
      Aof5ylUgIfjXqoq7M9zYCJP7Xqyd2Ngqb3/s88QnaO7VdZwDIL3RnNNryCWAPQeA
      v8yM/1oVslc7OGDgb2mjpzYBLj+X7qhP9UYw3oujB1wXMA2GDbT8mbLa22OUpA4=
      -----END CERTIFICATE-----
